export default interface ModItemType {
  "client_side": string,
  "server_side": string,
  "game_versions": string[],
  "id": string,
  "slug": string,
  "project_type": string,
  "team": string,
  "title": string,
  "description": string,
  "body": string,
  "published": string,
  "updated": string,
  "downloads": string,
  "followers": string,
  "categories": string[],
  "additional_categories": string[],
  "loaders": string[],
  "versions": string[],
  "icon_url": string,
  "issues_url": string,
  "source_url": string,
  "wiki_url": string,
  "discord_url": string,

}